language: node_js
node_js:
  - '6'
cache: yarn
install:
  - yarn install --frozen-lockfile
script:
  - yarn lint
  - yarn coverage
  - yarn build
after_success:
  - yarn global add codecov
  - codecov
